// ToDos move question to their own file.
// Add sorting into the array of objects
// Make sure to check that firstquestion and lastquestion are the lower and higher of the two, respectively
giftsAppsModule.service('Questions',[ '$rootScope', function( $rootScope ){

    var result = {"questions": [
        {"index": 1, "question": "rejoicing in God's provision even when the checkbook is in the red.", "category": "FTH", "score": null},
        {"index": 2, "question": "cleaning the kitchen once a week.", "category": "SVC", "score": null},
        {"index": 3, "question": "building sets for a drama.", "category": "CFT", "score": null},
        {"index": 4, "question": "searching the Bible to check the validity of a sermon or Bible lesson.", "category": "DSC", "score": null},
        {"index": 5, "question": "studying a demographic survey.", "category": "APS", "score": null},
        {"index": 6, "question": "welcoming an unexpected guest inside my house.", "category": "HSP", "score": null},
        {"index": 7, "question": "using creative ability (writing, art, drama, music) to benefit the body of Christ.", "category": "CCM", "score": null},
        {"index": 8, "question": "finding ways to make biblical content \"come alive\" for students.", "category": "TCH", "score": null},
        {"index": 9, "question": "calling to encourage a friend to stand strong in the faith.", "category": "ENC", "score": null},
        {"index": 10, "question": "helping with the emotional pain of the unemployed.", "category": "MCY", "score": null},
        {"index": 11, "question": "giving use of my car for youth retreats.", "category": "GVN", "score": null},
        {"index": 12, "question": "pleading the cause of God to people.", "category": "PRP", "score": null},
        {"index": 13, "question": "talking about Jesus to strangers who do not know Him.", "category": "EVN", "score": null},
        {"index": 14, "question": "motivating groups toward specific Bible objectives.", "category": "LDR", "score": null},
        {"index": 15, "question": "recognizing root problems keeping someone from growing spiritually.", "category": "XHT", "score": null},
        {"index": 16, "question": "being responsible for the spiritual lives of Christians.", "category": "SHP", "score": null},
        {"index": 17, "question": "organizing ideas, tasks, people and time for Christian service.", "category": "ADM", "score": null},
        {"index": 18, "question": "waiting as long as needed for the right job opening.", "category": "FTH", "score": null},
        {"index": 19, "question": "running lights for a drama.", "category": "SVC", "score": null},
        {"index": 20, "question": "designing better traffic flow for a system of classrooms.", "category": "CFT", "score": null},
        {"index": 21, "question": "recognizing when people are wearing \"masks\".", "category": "DSC", "score": null},
        {"index": 22, "question": "starting a new ministry.", "category": "APS", "score": null},
        {"index": 23, "question": "making strangers feel at ease at church or in my home.", "category": "HSP", "score": null},
        {"index": 24, "question": "expressing myself for God through artistic expression.", "category": "CCM", "score": null},
        {"index": 25, "question": "earnestly desiring to explain biblical principles to others.", "category": "TCH", "score": null},
        {"index": 26, "question": "helping a child ride a horse after having been thrown.", "category": "ENC", "score": null},
        {"index": 27, "question": "sympathizing with those who are experiencing hurt.", "category": "MCY", "score": null},
        {"index": 28, "question": "organizing and funding an appreciation dinner.", "category": "GVN", "score": null},
        {"index": 29, "question": "correcting wrong thinking in a friend.", "category": "PRP", "score": null},
        {"index": 30, "question": "confronting my friends and relatives to determine where they stand spiritually.", "category": "EVN", "score": null},
        {"index": 31, "question": "leading and directing people in an important ministry.", "category": "LDR", "score": null},
        {"index": 32, "question": "mapping out a plan of action for spiritual maturity in an individual.", "category": "XHT", "score": null},
        {"index": 33, "question": "nurturing and discipling people.", "category": "SHP", "score": null},
        {"index": 34, "question": "planning things where people are involved.", "category": "ADM", "score": null},
        {"index": 35, "question": "growing a garden from a seed.", "category": "FTH", "score": null},
        {"index": 36, "question": "setting up or taking down the chairs for a church banquet.", "category": "SVC", "score": null},
        {"index": 37, "question": "finding out what is wrong with a clock and repair it.", "category": "CFT", "score": null},
        {"index": 38, "question": "detecting phony or manipulative persons and teachings.", "category": "DSC", "score": null},
        {"index": 39, "question": "starting a new business.", "category": "APS", "score": null},
        {"index": 40, "question": "being more aware of other people's needs than my own.", "category": "HSP", "score": null},
        {"index": 41, "question": "finding unique ways to express truths of Scripture.", "category": "CCM", "score": null},
        {"index": 42, "question": "clarifying ideas for learners through careful study.", "category": "TCH", "score": null},
        {"index": 43, "question": "using scripture to give people help and courage.", "category": "ENC", "score": null},
        {"index": 44, "question": "working with people who suffer from physical, mental, or emotional problems.", "category": "MCY", "score": null},
        {"index": 45, "question": "giving when confronted with financial needs of God's kingdom.", "category": "GVN", "score": null},
        {"index": 46, "question": "relating spiritual insights from the Bible to people.", "category": "PRP", "score": null},
        {"index": 47, "question": "leading others to believe in Christ as their Savior.", "category": "EVN", "score": null},
        {"index": 48, "question": "leading and directing others toward goals.", "category": "LDR", "score": null},
        {"index": 49, "question": "being transparent in sharing areas of struggle.", "category": "XHT", "score": null},
        {"index": 50, "question": "assuming responsibility for a Christian being led astray.", "category": "SHP", "score": null},
        {"index": 51, "question": "making effective plans to accomplish goals.", "category": "ADM", "score": null},
        {"index": 52, "question": "trusting God to come through when things seem to be impossible.", "category": "FTH", "score": null},
        {"index": 53, "question": "doing dishes after a small group breakfast.", "category": "SVC", "score": null},
        {"index": 54, "question": "making a new pulpit for the new sanctuary.", "category": "CFT", "score": null},
        {"index": 55, "question": "looking beneath the surface and perceiving others' qualities.", "category": "DSC", "score": null},
        {"index": 56, "question": "responding to a long-term need in a new way.", "category": "APS", "score": null},
        {"index": 57, "question": "making my home available to those in need of hospitality.", "category": "HSP", "score": null},
        {"index": 58, "question": "leading the worship singing.", "category": "CCM", "score": null},
        {"index": 59, "question": "communicating excitement for an idea to a group of people.", "category": "TCH", "score": null},
        {"index": 60, "question": "writing notes to praise someone's performance.", "category": "ENC", "score": null},
        {"index": 61, "question": "detecting the emotional atmosphere of a group.", "category": "MCY", "score": null},
        {"index": 62, "question": "looking for new ways to give financially to the Lord's work.", "category": "GVN", "score": null},
        {"index": 63, "question": "proclaiming timely and urgent messages from God's Word.", "category": "PRP", "score": null},
        {"index": 64, "question": "ending conversations with clear closure.", "category": "EVN", "score": null},
        {"index": 65, "question": "presiding at a meeting to chart a new course.", "category": "LDR", "score": null},
        {"index": 66, "question": "giving personal feedback.", "category": "XHT", "score": null},
        {"index": 67, "question": "guiding other believers toward spiritual maturity.", "category": "SHP", "score": null},
        {"index": 68, "question": "coordinating the details necessary to meet a deadline.", "category": "ADM", "score": null},
        {"index": 69, "question": "trusting the safety rope while rope climbing.", "category": "FTH", "score": null},
        {"index": 70, "question": "stamping and filling envelopes for the church secretary.", "category": "SVC", "score": null},
        {"index": 71, "question": "wiring the speaker system for the church.", "category": "CFT", "score": null},
        {"index": 72, "question": "being able to discriminate between good and evil.", "category": "DSC", "score": null},
        {"index": 73, "question": "designing a storage closet for future needs.", "category": "APS", "score": null},
        {"index": 74, "question": "introducing myself to a new neighbor doing yard work.", "category": "HSP", "score": null},
        {"index": 75, "question": "innovating.", "category": "CCM", "score": null},
        {"index": 76, "question": "breaking large concepts into understandable pieces.", "category": "TCH", "score": null},
        {"index": 77, "question": "spending some time in a counseling ministry.", "category": "ENC", "score": null},
        {"index": 78, "question": "watching someone heal from the loss of a parent.", "category": "MCY", "score": null},
        {"index": 79, "question": "living more simply to give to God's work.", "category": "GVN", "score": null},
        {"index": 80, "question": "building up, encouraging, and comforting Christians by speaking to them of spiritual things.", "category": "PRP", "score": null},
        {"index": 81, "question": "sharing my beliefs in a clear and meaningful way.", "category": "EVN", "score": null},
        {"index": 82, "question": "bearing the brunt of criticism for the team's failure.", "category": "LDR", "score": null},
        {"index": 83, "question": "speaking the truth in love.", "category": "XHT", "score": null},
        {"index": 84, "question": "equipping people to do ministry.", "category": "SHP", "score": null},
        {"index": 85, "question": "delegating important tasks to the right people at the right time.", "category": "ADM", "score": null},
        {"index": 86, "question": "taking out a loan for a college education.", "category": "FTH", "score": null},
        {"index": 87, "question": "arriving early Sunday morning to get the coffee going.", "category": "SVC", "score": null},
        {"index": 88, "question": "helping a child build a doll house.", "category": "CFT", "score": null},
        {"index": 89, "question": "perceiving ramifications of a new law.", "category": "DSC", "score": null},
        {"index": 90, "question": "developing an appropriate form/function chart of company employees.", "category": "APS", "score": null},
        {"index": 91, "question": "having a genuine appreciation for each guest I minister to.", "category": "HSP", "score": null},
        {"index": 92, "question": "determining feelings which Bible passages bring out.", "category": "CCM", "score": null},
        {"index": 93, "question": "discovering new ideas to share with others.", "category": "TCH", "score": null},
        {"index": 94, "question": "helping hurting people see God's answers to life's problems.", "category": "ENC", "score": null},
        {"index": 95, "question": "sensing when people are hurting and feeling their pain.", "category": "MCY", "score": null},
        {"index": 96, "question": "paying rent for a family whose breadwinner has been laid off.", "category": "GVN", "score": null},
        {"index": 97, "question": "speaking out on the moral issues of the day such as abortion, teen sex, and racism.", "category": "PRP", "score": null},
        {"index": 98, "question": "listening critically and carefully to someones beliefs.", "category": "EVN", "score": null},
        {"index": 99, "question": "sensing when a group is spinning its wheels and do something about it.", "category": "LDR", "score": null},
        {"index": 100, "question": "defining key issues facing a team.", "category": "XHT", "score": null},
        {"index": 101, "question": "working to help a group bond together.", "category": "SHP", "score": null},
        {"index": 102, "question": "deciding when to implement projects or ministries.", "category": "ADM", "score": null}
    ]
    };
    return result;
}]);

